import { Project } from '@/types';

export const MOCK_PROJECTS: Project[] = [
  {
    id: 'PRJ-001',
    name: 'NH-48 Highway Widening Project',
    client: 'National Highways Authority of India',
    location: 'Bengaluru – Mysuru Corridor, Karnataka',
    type: 'Highway Expansion',
    priority: 'critical',
    value: 4850,
    description: 'Expansion of NH-48 from 4-lane to 6-lane highway covering 62km stretch with elevated sections at key intersections.',
    area: 248000,
    currentStage: 'accounts',
    createdAt: '2026-01-10T09:00:00Z',
    updatedAt: '2026-06-20T14:30:00Z',
    stages: {
      sales: { status: 'completed', completedAt: '2026-01-12T10:00:00Z', notes: 'Lead confirmed. Survey required.', assignedTo: 'Priya Sharma' },
      survey: { status: 'completed', completedAt: '2026-02-05T16:00:00Z', notes: 'Site survey completed. Mapping required.', assignedTo: 'Ravi Kumar' },
      mapping: { status: 'completed', completedAt: '2026-03-15T11:00:00Z', notes: 'Topographic maps delivered.', assignedTo: 'Sneha Patel' },
      drafting: { status: 'completed', completedAt: '2026-05-01T09:00:00Z', notes: 'Full CAD drawings approved.', assignedTo: 'Anil Desai' },
      accounts: { status: 'in_progress', assignedTo: 'Kavitha Nair' },
    },
  },
  {
    id: 'PRJ-002',
    name: 'Cauvery River Bridge Reconstruction',
    client: 'Karnataka PWD',
    location: 'Shivanasamudra, Mandya District',
    type: 'Bridge Engineering',
    priority: 'high',
    value: 1240,
    description: 'Reconstruction of aging colonial-era bridge with modern pre-stressed concrete girder design. Span: 180m.',
    area: 5400,
    currentStage: 'drafting',
    createdAt: '2026-02-14T08:00:00Z',
    updatedAt: '2026-06-18T10:00:00Z',
    stages: {
      sales: { status: 'completed', completedAt: '2026-02-16T12:00:00Z', notes: 'Lead confirmed. Survey required.', assignedTo: 'Priya Sharma' },
      survey: { status: 'completed', completedAt: '2026-03-10T15:00:00Z', notes: 'Hydrological survey done. Mapping required.', assignedTo: 'Ravi Kumar' },
      mapping: { status: 'completed', completedAt: '2026-04-20T13:00:00Z', notes: 'River bed mapping complete.', assignedTo: 'Sneha Patel' },
      drafting: { status: 'in_progress', assignedTo: 'Anil Desai' },
      accounts: { status: 'pending' },
    },
  },
  {
    id: 'PRJ-003',
    name: 'Koramangala Storm Water Drain Network',
    client: 'BBMP Infrastructure Division',
    location: 'Koramangala, Bengaluru',
    type: 'Drainage System',
    priority: 'high',
    value: 320,
    description: 'Design and construction supervision for a 14km underground storm water drain to prevent seasonal flooding.',
    area: 42000,
    currentStage: 'mapping',
    createdAt: '2026-03-01T10:00:00Z',
    updatedAt: '2026-06-15T09:00:00Z',
    stages: {
      sales: { status: 'completed', completedAt: '2026-03-03T11:00:00Z', notes: 'Lead confirmed. Survey required.', assignedTo: 'Priya Sharma' },
      survey: { status: 'completed', completedAt: '2026-04-01T16:00:00Z', notes: 'Survey done. Mapping required.', assignedTo: 'Ravi Kumar' },
      mapping: { status: 'in_progress', assignedTo: 'Sneha Patel' },
      drafting: { status: 'pending' },
      accounts: { status: 'pending' },
    },
  },
  {
    id: 'PRJ-004',
    name: 'Indiranagar Metro Station Structural Audit',
    client: 'Namma Metro Rail Corporation',
    location: 'Indiranagar, Bengaluru',
    type: 'Structural Audit',
    priority: 'critical',
    value: 85,
    description: 'Comprehensive structural integrity assessment of the Indiranagar metro station and elevated viaduct spanning 2.3km.',
    area: 12000,
    currentStage: 'accounts',
    createdAt: '2026-01-20T07:00:00Z',
    updatedAt: '2026-06-22T14:00:00Z',
    stages: {
      sales: { status: 'completed', completedAt: '2026-01-22T09:00:00Z', notes: 'Lead confirmed. No survey required — in-house inspection.', assignedTo: 'Priya Sharma' },
      survey: { status: 'bypassed', notes: 'Survey bypassed by Sales decision.' },
      mapping: { status: 'completed', completedAt: '2026-02-28T11:00:00Z', notes: 'Structural maps complete.', assignedTo: 'Sneha Patel' },
      drafting: { status: 'completed', completedAt: '2026-04-10T15:00:00Z', notes: 'Audit drawings finalized.', assignedTo: 'Anil Desai' },
      accounts: { status: 'in_progress', assignedTo: 'Kavitha Nair' },
    },
  },
  {
    id: 'PRJ-005',
    name: 'Whitefield IT Corridor Road Improvement',
    client: 'KIADB',
    location: 'Whitefield, Bengaluru',
    type: 'Road Construction',
    priority: 'medium',
    value: 560,
    description: 'Road widening and surface improvement for 18km of arterial roads in the Whitefield IT hub.',
    area: 90000,
    currentStage: 'survey',
    createdAt: '2026-04-10T09:00:00Z',
    updatedAt: '2026-06-10T11:00:00Z',
    stages: {
      sales: { status: 'completed', completedAt: '2026-04-12T10:00:00Z', notes: 'Lead confirmed. Survey required.', assignedTo: 'Priya Sharma' },
      survey: { status: 'in_progress', assignedTo: 'Ravi Kumar' },
      mapping: { status: 'pending' },
      drafting: { status: 'pending' },
      accounts: { status: 'pending' },
    },
  },
  {
    id: 'PRJ-006',
    name: 'Tumkur Industrial Estate Layout',
    client: 'KIADB Tumkur',
    location: 'Tumkur, Karnataka',
    type: 'Residential Layout',
    priority: 'medium',
    value: 920,
    description: 'Master planning and layout design for a 200-acre industrial estate with internal road network and utilities.',
    area: 810000,
    currentStage: 'sales',
    createdAt: '2026-06-01T08:00:00Z',
    updatedAt: '2026-06-01T08:00:00Z',
    stages: {
      sales: { status: 'in_progress', assignedTo: 'Priya Sharma' },
      survey: { status: 'pending' },
      mapping: { status: 'pending' },
      drafting: { status: 'pending' },
      accounts: { status: 'pending' },
    },
  },
  {
    id: 'PRJ-007',
    name: 'Mangaluru Port Access Road',
    client: 'New Mangalore Port Trust',
    location: 'Mangaluru, Karnataka',
    type: 'Road Construction',
    priority: 'high',
    value: 780,
    description: 'Construction of a 12km dedicated access road connecting NH-75 to the port facility.',
    area: 72000,
    currentStage: 'survey',
    createdAt: '2026-03-20T10:00:00Z',
    updatedAt: '2026-06-05T08:00:00Z',
    stages: {
      sales: { status: 'completed', completedAt: '2026-03-22T12:00:00Z', notes: 'Lead confirmed. Survey required.', assignedTo: 'Priya Sharma' },
      survey: { status: 'in_progress', assignedTo: 'Ravi Kumar' },
      mapping: { status: 'pending' },
      drafting: { status: 'pending' },
      accounts: { status: 'pending' },
    },
  },
  {
    id: 'PRJ-008',
    name: 'Mysuru Palace Zone Water Supply Revamp',
    client: 'Mysuru City Corporation',
    location: 'Mysuru Heritage Zone, Karnataka',
    type: 'Water Treatment',
    priority: 'high',
    value: 430,
    description: 'Replacement of century-old water mains in the heritage zone with modern HDPE pipes — heritage structure sensitivity required.',
    area: 28000,
    currentStage: 'accounts',
    createdAt: '2026-01-05T09:00:00Z',
    updatedAt: '2026-06-01T11:00:00Z',
    stages: {
      sales: { status: 'completed', completedAt: '2026-01-07T10:00:00Z', notes: 'Lead confirmed. Survey required.', assignedTo: 'Priya Sharma' },
      survey: { status: 'completed', completedAt: '2026-01-30T15:00:00Z', notes: 'Survey done. No mapping required — existing records sufficient.', assignedTo: 'Ravi Kumar' },
      mapping: { status: 'bypassed', notes: 'Mapping bypassed by Survey decision.' },
      drafting: { status: 'bypassed', notes: 'Drafting bypassed by Survey decision.' },
      accounts: { status: 'in_progress', assignedTo: 'Kavitha Nair' },
    },
  },
  {
    id: 'PRJ-009',
    name: 'Kochi Flyover Design – Edappally Junction',
    client: 'Kerala Roads & Bridges Development Corporation',
    location: 'Edappally, Kochi, Kerala',
    type: 'Flyover Design',
    priority: 'critical',
    value: 2100,
    description: 'Detailed engineering design of a 4-level cloverleaf interchange to resolve chronic traffic bottleneck at Edappally.',
    area: 18000,
    currentStage: 'mapping',
    createdAt: '2026-02-28T09:00:00Z',
    updatedAt: '2026-06-12T13:00:00Z',
    stages: {
      sales: { status: 'completed', completedAt: '2026-03-01T11:00:00Z', notes: 'Lead confirmed. Survey required.', assignedTo: 'Priya Sharma' },
      survey: { status: 'completed', completedAt: '2026-04-15T14:00:00Z', notes: 'Survey complete. Mapping required.', assignedTo: 'Ravi Kumar' },
      mapping: { status: 'in_progress', assignedTo: 'Sneha Patel' },
      drafting: { status: 'pending' },
      accounts: { status: 'pending' },
    },
  },
  {
    id: 'PRJ-010',
    name: 'Hubli-Dharwad Peripheral Ring Road',
    client: 'Hubli-Dharwad Municipal Corporation',
    location: 'Hubli-Dharwad Twin Cities, Karnataka',
    type: 'Road Construction',
    priority: 'medium',
    value: 1650,
    description: 'Design consultancy for 54km peripheral ring road bypassing city centres to ease urban traffic.',
    area: 270000,
    currentStage: 'sales',
    createdAt: '2026-06-10T09:00:00Z',
    updatedAt: '2026-06-10T09:00:00Z',
    stages: {
      sales: { status: 'in_progress', assignedTo: 'Priya Sharma' },
      survey: { status: 'pending' },
      mapping: { status: 'pending' },
      drafting: { status: 'pending' },
      accounts: { status: 'pending' },
    },
  },
  {
    id: 'PRJ-011',
    name: 'Bengaluru Outer Ring Road Land Survey',
    client: 'BDA – Bengaluru Development Authority',
    location: 'ORR Stretch, Bengaluru',
    type: 'Land Survey',
    priority: 'high',
    value: 145,
    description: 'Demarcation and cadastral survey of 38km ORR corridor for land acquisition proceedings.',
    area: 152000,
    currentStage: 'accounts',
    createdAt: '2026-01-15T08:00:00Z',
    updatedAt: '2026-05-30T16:00:00Z',
    stages: {
      sales: { status: 'completed', completedAt: '2026-01-17T09:00:00Z', notes: 'Lead confirmed. Survey required.', assignedTo: 'Priya Sharma' },
      survey: { status: 'completed', completedAt: '2026-02-20T14:00:00Z', notes: 'Land survey complete. No mapping required.', assignedTo: 'Ravi Kumar' },
      mapping: { status: 'bypassed', notes: 'Mapping bypassed by Survey decision.' },
      drafting: { status: 'bypassed', notes: 'Drafting bypassed by Survey decision.' },
      accounts: { status: 'completed', completedAt: '2026-05-30T16:00:00Z', notes: 'Final invoice cleared.', assignedTo: 'Kavitha Nair' },
    },
  },
  {
    id: 'PRJ-012',
    name: 'Yeshwanthpur Commercial Tower Foundation Audit',
    client: 'Prestige Estates Projects Ltd.',
    location: 'Yeshwanthpur, Bengaluru',
    type: 'Structural Audit',
    priority: 'medium',
    value: 62,
    description: 'Structural audit of existing foundation for a planned 32-storey mixed-use tower on a heritage warehouse site.',
    area: 4200,
    currentStage: 'drafting',
    createdAt: '2026-04-25T10:00:00Z',
    updatedAt: '2026-06-20T12:00:00Z',
    stages: {
      sales: { status: 'completed', completedAt: '2026-04-27T11:00:00Z', notes: 'Lead confirmed. No survey required.', assignedTo: 'Priya Sharma' },
      survey: { status: 'bypassed', notes: 'Survey bypassed by Sales decision.' },
      mapping: { status: 'completed', completedAt: '2026-05-20T15:00:00Z', notes: 'Foundation mapping complete.', assignedTo: 'Sneha Patel' },
      drafting: { status: 'in_progress', assignedTo: 'Anil Desai' },
      accounts: { status: 'pending' },
    },
  },
  {
    id: 'PRJ-013',
    name: 'Davangere Smart City Road Grid',
    client: 'Davangere Smart City Ltd.',
    location: 'Davangere, Karnataka',
    type: 'Road Construction',
    priority: 'medium',
    value: 890,
    description: 'Design of 32km smart road network with embedded IoT sensors, smart signals, and utility ducts.',
    area: 192000,
    currentStage: 'sales',
    createdAt: '2026-06-18T09:00:00Z',
    updatedAt: '2026-06-18T09:00:00Z',
    stages: {
      sales: { status: 'in_progress', assignedTo: 'Priya Sharma' },
      survey: { status: 'pending' },
      mapping: { status: 'pending' },
      drafting: { status: 'pending' },
      accounts: { status: 'pending' },
    },
  },
  {
    id: 'PRJ-014',
    name: 'Shimoga Bhadravathi Industrial Water Pipeline',
    client: 'KSSIDC',
    location: 'Shimoga – Bhadravathi, Karnataka',
    type: 'Water Treatment',
    priority: 'low',
    value: 210,
    description: 'Design of 28km raw water transmission pipeline from Tunga River to serve 4 industrial clusters.',
    area: 84000,
    currentStage: 'survey',
    createdAt: '2026-05-01T10:00:00Z',
    updatedAt: '2026-06-08T14:00:00Z',
    stages: {
      sales: { status: 'completed', completedAt: '2026-05-03T12:00:00Z', notes: 'Lead confirmed. Survey required.', assignedTo: 'Priya Sharma' },
      survey: { status: 'in_progress', assignedTo: 'Ravi Kumar' },
      mapping: { status: 'pending' },
      drafting: { status: 'pending' },
      accounts: { status: 'pending' },
    },
  },
  {
    id: 'PRJ-015',
    name: 'Bangalore Airport Metro Phase III',
    client: 'BMRCL',
    location: 'Kempegowda International Airport Zone, Bengaluru',
    type: 'Bridge Engineering',
    priority: 'critical',
    value: 7200,
    description: 'Structural design consultancy for 22km elevated metro corridor connecting Hebbal to KIAL with 8 stations.',
    area: 88000,
    currentStage: 'mapping',
    createdAt: '2026-02-01T08:00:00Z',
    updatedAt: '2026-06-23T11:00:00Z',
    stages: {
      sales: { status: 'completed', completedAt: '2026-02-03T10:00:00Z', notes: 'Lead confirmed. Survey required.', assignedTo: 'Priya Sharma' },
      survey: { status: 'completed', completedAt: '2026-03-20T15:00:00Z', notes: 'Aerial and ground survey done. Mapping required.', assignedTo: 'Ravi Kumar' },
      mapping: { status: 'in_progress', assignedTo: 'Sneha Patel' },
      drafting: { status: 'pending' },
      accounts: { status: 'pending' },
    },
  },
];
