import { Project } from '@/types';

const bp = (status: 'bypassed') => ({ status, completedAt: '2026-01-01T00:00:00Z' });

export const MOCK_PROJECTS: Project[] = [
  // ── MARKING workflow: Survey + Mapping notified simultaneously ─────────
  {
    id: 'PRJ-001',
    name: 'NH-48 Highway Widening Project',
    client: 'National Highways Authority of India',
    clientPhone: '+91 11 2307 5000',
    location: 'Bengaluru – Mysuru Corridor, Karnataka',
    type: 'Highway Expansion',
    workflowType: 'marking',
    priority: 'critical',
    value: 4850000,
    description: 'Expansion of NH-48 from 4-lane to 6-lane highway covering 62km stretch.',
    scheduledDate: '2026-07-15T09:00:00Z',
    currentStage: 'accounts',
    createdAt: '2026-01-10T09:00:00Z',
    updatedAt: '2026-06-20T14:30:00Z',
    stages: {
      sales:         { status: 'completed', completedAt: '2026-01-12T10:00:00Z', notes: 'Lead confirmed. Marking workflow.', assignedTo: 'Priya Sharma' },
      survey:        { status: 'completed', completedAt: '2026-02-05T16:00:00Z', notes: 'Field survey complete.', assignedTo: 'Ravi Kumar', scheduledDate: '2026-01-28T09:00:00Z' },
      mapping:       { status: 'completed', completedAt: '2026-03-15T11:00:00Z', notes: 'Site mapping complete.', assignedTo: 'Sneha Patel', scheduledDate: '2026-01-28T09:00:00Z' },
      drawing:       bp('bypassed'),
      visualization: bp('bypassed'),
      qs_boq:        { status: 'bypassed' },
      accounts:      { status: 'in_progress', assignedTo: 'Kavitha Nair' },
    },
  },
  {
    id: 'PRJ-002',
    name: 'Cauvery River Bridge Reconstruction',
    client: 'Karnataka PWD',
    clientPhone: '+91 80 2225 8100',
    location: 'Shivanasamudra, Mandya District',
    type: 'Bridge Engineering',
    workflowType: 'marking',
    priority: 'high',
    value: 1240000,
    description: 'Reconstruction of aging bridge with modern pre-stressed concrete girder design.',
    scheduledDate: '2026-07-20T09:00:00Z',
    currentStage: 'survey',
    createdAt: '2026-02-14T08:00:00Z',
    updatedAt: '2026-06-18T10:00:00Z',
    stages: {
      sales:         { status: 'completed', completedAt: '2026-02-16T12:00:00Z', notes: 'Lead confirmed. Marking workflow — Survey + Mapping notified.', assignedTo: 'Priya Sharma' },
      survey:        { status: 'in_progress', assignedTo: 'Ravi Kumar', scheduledDate: '2026-07-20T09:00:00Z' },
      mapping:       { status: 'in_progress', assignedTo: 'Sneha Patel', scheduledDate: '2026-07-20T09:00:00Z' },
      drawing:       bp('bypassed'),
      visualization: bp('bypassed'),
      qs_boq:        { status: 'bypassed' },
      accounts:      { status: 'pending' },
    },
  },
  {
    id: 'PRJ-003',
    name: 'Koramangala Storm Water Drain Network',
    client: 'BBMP Infrastructure Division',
    clientPhone: '+91 80 2299 2001',
    location: 'Koramangala, Bengaluru',
    type: 'Drainage System',
    workflowType: 'mapping',
    priority: 'high',
    value: 320000,
    description: 'Design of 14km underground storm water drain to prevent seasonal flooding.',
    scheduledDate: '2026-07-25T09:00:00Z',
    currentStage: 'mapping',
    createdAt: '2026-03-01T10:00:00Z',
    updatedAt: '2026-06-15T09:00:00Z',
    stages: {
      sales:         { status: 'completed', completedAt: '2026-03-03T11:00:00Z', notes: 'Lead confirmed. Mapping workflow.', assignedTo: 'Priya Sharma' },
      survey:        { status: 'completed', completedAt: '2026-04-01T16:00:00Z', notes: 'Survey done.', assignedTo: 'Ravi Kumar', scheduledDate: '2026-03-25T09:00:00Z' },
      mapping:       { status: 'in_progress', assignedTo: 'Sneha Patel', scheduledDate: '2026-07-25T09:00:00Z' },
      drawing:       bp('bypassed'),
      visualization: bp('bypassed'),
      qs_boq:        { status: 'bypassed' },
      accounts:      { status: 'pending' },
    },
  },
  {
    id: 'PRJ-004',
    name: 'Indiranagar Metro Station Structural Audit',
    client: 'Namma Metro Rail Corporation',
    clientPhone: '+91 80 4204 0000',
    location: 'Indiranagar, Bengaluru',
    type: 'Structural Audit',
    workflowType: 'mapping',
    priority: 'critical',
    value: 85000,
    description: 'Structural integrity assessment of metro station and elevated viaduct.',
    currentStage: 'accounts',
    createdAt: '2026-01-20T07:00:00Z',
    updatedAt: '2026-06-22T14:00:00Z',
    stages: {
      sales:         { status: 'completed', completedAt: '2026-01-22T09:00:00Z', notes: 'Lead confirmed. Mapping workflow.', assignedTo: 'Priya Sharma' },
      survey:        { status: 'completed', completedAt: '2026-02-10T11:00:00Z', notes: 'Survey complete.', assignedTo: 'Ravi Kumar', scheduledDate: '2026-02-05T09:00:00Z' },
      mapping:       { status: 'completed', completedAt: '2026-03-28T11:00:00Z', notes: 'Structural maps complete.', assignedTo: 'Sneha Patel', scheduledDate: '2026-03-20T09:00:00Z' },
      drawing:       bp('bypassed'),
      visualization: bp('bypassed'),
      qs_boq:        { status: 'bypassed' },
      accounts:      { status: 'in_progress', assignedTo: 'Kavitha Nair' },
    },
  },
  {
    id: 'PRJ-005',
    name: 'Whitefield IT Corridor Road Improvement',
    client: 'KIADB',
    clientPhone: '+91 80 2295 5555',
    location: 'Whitefield, Bengaluru',
    type: 'Road Construction',
    workflowType: 'marking',
    priority: 'medium',
    value: 560000,
    description: 'Road widening for 18km of arterial roads in Whitefield IT hub.',
    scheduledDate: '2026-08-10T09:00:00Z',
    currentStage: 'survey',
    createdAt: '2026-04-10T09:00:00Z',
    updatedAt: '2026-06-10T11:00:00Z',
    stages: {
      sales:         { status: 'completed', completedAt: '2026-04-12T10:00:00Z', notes: 'Lead confirmed. Marking — Survey + Mapping notified.', assignedTo: 'Priya Sharma' },
      survey:        { status: 'in_progress', assignedTo: 'Ravi Kumar', scheduledDate: '2026-08-10T09:00:00Z' },
      mapping:       { status: 'in_progress', assignedTo: 'Sneha Patel', scheduledDate: '2026-08-10T09:00:00Z' },
      drawing:       bp('bypassed'),
      visualization: bp('bypassed'),
      qs_boq:        { status: 'bypassed' },
      accounts:      { status: 'pending' },
    },
  },
  {
    id: 'PRJ-006',
    name: 'Tumkur Industrial Estate Layout',
    client: 'KIADB Tumkur',
    clientPhone: '+91 816 222 5000',
    location: 'Tumkur, Karnataka',
    type: 'Residential Layout',
    workflowType: 'drawing',
    priority: 'medium',
    value: 920000,
    description: 'Master planning and layout design for 200-acre industrial estate.',
    deadline: '2027-06-30T00:00:00Z',
    currentStage: 'sales',
    createdAt: '2026-06-01T08:00:00Z',
    updatedAt: '2026-06-01T08:00:00Z',
    stages: {
      sales:         { status: 'in_progress', assignedTo: 'Priya Sharma' },
      survey:        bp('bypassed'),
      mapping:       bp('bypassed'),
      drawing:       { status: 'pending' },
      visualization: bp('bypassed'),
      qs_boq:        { status: 'bypassed' },
      accounts:      { status: 'pending' },
    },
  },
  {
    id: 'PRJ-007',
    name: 'Mangaluru Port Access Road',
    client: 'New Mangalore Port Trust',
    clientPhone: '+91 824 240 4000',
    location: 'Mangaluru, Karnataka',
    type: 'Road Construction',
    workflowType: 'marking',
    priority: 'high',
    value: 780000,
    description: 'Construction of 12km dedicated access road to port facility.',
    scheduledDate: '2026-07-30T09:00:00Z',
    currentStage: 'survey',
    createdAt: '2026-03-20T10:00:00Z',
    updatedAt: '2026-06-05T08:00:00Z',
    stages: {
      sales:         { status: 'completed', completedAt: '2026-03-22T12:00:00Z', notes: 'Lead confirmed. Marking workflow.', assignedTo: 'Priya Sharma' },
      survey:        { status: 'in_progress', assignedTo: 'Ravi Kumar', scheduledDate: '2026-07-30T09:00:00Z' },
      mapping:       { status: 'in_progress', assignedTo: 'Sneha Patel', scheduledDate: '2026-07-30T09:00:00Z' },
      drawing:       bp('bypassed'),
      visualization: bp('bypassed'),
      qs_boq:        { status: 'bypassed' },
      accounts:      { status: 'pending' },
    },
  },
  {
    id: 'PRJ-008',
    name: 'Mysuru Palace Zone Water Supply Revamp',
    client: 'Mysuru City Corporation',
    clientPhone: '+91 821 242 0000',
    location: 'Mysuru Heritage Zone, Karnataka',
    type: 'Water Treatment',
    workflowType: 'mapping',
    priority: 'high',
    value: 430000,
    description: 'Replacement of century-old water mains with modern HDPE pipes.',
    currentStage: 'accounts',
    createdAt: '2026-01-05T09:00:00Z',
    updatedAt: '2026-06-01T11:00:00Z',
    stages: {
      sales:         { status: 'completed', completedAt: '2026-01-07T10:00:00Z', notes: 'Lead confirmed.', assignedTo: 'Priya Sharma' },
      survey:        { status: 'completed', completedAt: '2026-01-30T15:00:00Z', notes: 'Survey done.', assignedTo: 'Ravi Kumar', scheduledDate: '2026-01-25T09:00:00Z' },
      mapping:       { status: 'completed', completedAt: '2026-02-20T11:00:00Z', notes: 'Mapping complete.', assignedTo: 'Sneha Patel', scheduledDate: '2026-02-15T09:00:00Z' },
      drawing:       bp('bypassed'),
      visualization: bp('bypassed'),
      qs_boq:        { status: 'bypassed' },
      accounts:      { status: 'in_progress', assignedTo: 'Kavitha Nair' },
    },
  },
  {
    id: 'PRJ-009',
    name: 'Kochi Flyover Design – Edappally Junction',
    client: 'Kerala Roads & Bridges Development Corporation',
    clientPhone: '+91 471 251 4000',
    location: 'Edappally, Kochi, Kerala',
    type: 'Flyover Design',
    workflowType: 'drawing',
    priority: 'critical',
    value: 2100000,
    description: 'Detailed engineering design of a 4-level cloverleaf interchange.',
    deadline: '2026-12-15T00:00:00Z',
    currentStage: 'drawing',
    createdAt: '2026-02-28T09:00:00Z',
    updatedAt: '2026-06-12T13:00:00Z',
    stages: {
      sales:         { status: 'completed', completedAt: '2026-03-01T11:00:00Z', notes: 'Lead confirmed. Drawing workflow.', assignedTo: 'Priya Sharma' },
      survey:        bp('bypassed'),
      mapping:       bp('bypassed'),
      drawing:       { status: 'in_progress', assignedTo: 'Anil Desai' },
      visualization: bp('bypassed'),
      qs_boq:        { status: 'bypassed' },
      accounts:      { status: 'pending' },
    },
  },
  {
    id: 'PRJ-010',
    name: 'Hubli-Dharwad Peripheral Ring Road',
    client: 'Hubli-Dharwad Municipal Corporation',
    clientPhone: '+91 836 221 2000',
    location: 'Hubli-Dharwad Twin Cities, Karnataka',
    type: 'Road Construction',
    workflowType: 'marking',
    priority: 'medium',
    value: 1650000,
    description: 'Design consultancy for 54km peripheral ring road.',
    scheduledDate: '2026-09-05T09:00:00Z',
    currentStage: 'sales',
    createdAt: '2026-06-10T09:00:00Z',
    updatedAt: '2026-06-10T09:00:00Z',
    stages: {
      sales:         { status: 'in_progress', assignedTo: 'Priya Sharma' },
      survey:        { status: 'pending' },
      mapping:       { status: 'pending' },
      drawing:       bp('bypassed'),
      visualization: bp('bypassed'),
      qs_boq:        { status: 'bypassed' },
      accounts:      { status: 'pending' },
    },
  },
  {
    id: 'PRJ-011',
    name: 'Bengaluru Outer Ring Road Land Survey',
    client: 'BDA – Bengaluru Development Authority',
    clientPhone: '+91 80 2295 7600',
    location: 'ORR Stretch, Bengaluru',
    type: 'Land Survey',
    workflowType: 'marking',
    priority: 'high',
    value: 145000,
    description: 'Demarcation and cadastral survey of 38km ORR corridor.',
    currentStage: 'accounts',
    createdAt: '2026-01-15T08:00:00Z',
    updatedAt: '2026-05-30T16:00:00Z',
    stages: {
      sales:         { status: 'completed', completedAt: '2026-01-17T09:00:00Z', assignedTo: 'Priya Sharma' },
      survey:        { status: 'completed', completedAt: '2026-02-20T14:00:00Z', assignedTo: 'Ravi Kumar', scheduledDate: '2026-02-15T09:00:00Z' },
      mapping:       { status: 'completed', completedAt: '2026-03-10T11:00:00Z', assignedTo: 'Sneha Patel', scheduledDate: '2026-03-05T09:00:00Z' },
      drawing:       bp('bypassed'),
      visualization: bp('bypassed'),
      qs_boq:        { status: 'bypassed' },
      accounts:      { status: 'completed', completedAt: '2026-05-30T16:00:00Z', notes: 'Final invoice cleared.', assignedTo: 'Kavitha Nair' },
    },
  },
  {
    id: 'PRJ-012',
    name: 'Yeshwanthpur Commercial Tower 3D Visualization',
    client: 'Prestige Estates Projects Ltd.',
    clientPhone: '+91 80 2572 5000',
    location: 'Yeshwanthpur, Bengaluru',
    type: 'Structural Audit',
    workflowType: 'visualization',
    priority: 'medium',
    value: 62000,
    description: '3D visualization and renders for a planned 32-storey mixed-use tower.',
    deadline: '2026-09-15T00:00:00Z',
    currentStage: 'visualization',
    createdAt: '2026-04-25T10:00:00Z',
    updatedAt: '2026-06-20T12:00:00Z',
    stages: {
      sales:         { status: 'completed', completedAt: '2026-04-27T11:00:00Z', notes: 'Lead confirmed. 3D Viz workflow.', assignedTo: 'Priya Sharma' },
      survey:        bp('bypassed'),
      mapping:       bp('bypassed'),
      drawing:       bp('bypassed'),
      visualization: { status: 'in_progress', assignedTo: 'Meena Krishnan' },
      qs_boq:        { status: 'bypassed' },
      accounts:      { status: 'pending' },
    },
  },
  {
    id: 'PRJ-013',
    name: 'Davangere Smart City Road Grid',
    client: 'Davangere Smart City Ltd.',
    clientPhone: '+91 8192 231 000',
    location: 'Davangere, Karnataka',
    type: 'Road Construction',
    workflowType: 'drawing',
    priority: 'medium',
    value: 890000,
    description: 'Design of 32km smart road network with IoT sensors.',
    deadline: '2027-04-30T00:00:00Z',
    currentStage: 'sales',
    createdAt: '2026-06-18T09:00:00Z',
    updatedAt: '2026-06-18T09:00:00Z',
    stages: {
      sales:         { status: 'in_progress', assignedTo: 'Priya Sharma' },
      survey:        bp('bypassed'),
      mapping:       bp('bypassed'),
      drawing:       { status: 'pending' },
      visualization: bp('bypassed'),
      qs_boq:        { status: 'bypassed' },
      accounts:      { status: 'pending' },
    },
  },
  {
    id: 'PRJ-014',
    name: 'Shimoga Water Pipeline – CANCELLED',
    client: 'KSSIDC',
    clientPhone: '+91 8182 224 000',
    location: 'Shimoga – Bhadravathi, Karnataka',
    type: 'Water Treatment',
    workflowType: 'mapping',
    priority: 'low',
    value: 210000,
    description: 'Design of 28km raw water transmission pipeline.',
    scheduledDate: '2026-08-01T09:00:00Z',
    currentStage: 'survey',
    createdAt: '2026-05-01T10:00:00Z',
    updatedAt: '2026-06-08T14:00:00Z',
    stages: {
      sales:         { status: 'completed', completedAt: '2026-05-03T12:00:00Z', notes: 'Lead confirmed.', assignedTo: 'Priya Sharma' },
      survey:        { status: 'cancelled', assignedTo: 'Ravi Kumar', scheduledDate: '2026-08-01T09:00:00Z', cancelReason: 'Client requested postponement due to budget review.' },
      mapping:       { status: 'pending' },
      drawing:       bp('bypassed'),
      visualization: bp('bypassed'),
      qs_boq:        { status: 'bypassed' },
      accounts:      { status: 'pending' },
    },
  },
  {
    id: 'PRJ-015',
    name: 'Bangalore Airport Metro Phase III',
    client: 'BMRCL',
    clientPhone: '+91 80 2296 6900',
    location: 'Kempegowda International Airport Zone, Bengaluru',
    type: 'Bridge Engineering',
    workflowType: 'visualization',
    priority: 'critical',
    value: 7200000,
    description: 'Structural design and 3D visualization for 22km elevated metro corridor.',
    deadline: '2027-12-31T00:00:00Z',
    currentStage: 'sales',
    createdAt: '2026-07-01T08:00:00Z',
    updatedAt: '2026-07-01T08:00:00Z',
    stages: {
      sales:         { status: 'in_progress', assignedTo: 'Priya Sharma' },
      survey:        bp('bypassed'),
      mapping:       bp('bypassed'),
      drawing:       bp('bypassed'),
      visualization: { status: 'pending' },
      qs_boq:        { status: 'bypassed' },
      accounts:      { status: 'pending' },
    },
  },
];
